[build]
  functions = "functions"
  publish = "public"

[functions]
  included_files = ["src/views/**/*.ejs", "data/*.json"]
  external_node_modules = ["ejs"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
